name: osm-github-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - cartopy
  - geoviews
  - hvplot
  - matplotlib
  - xarray
  - intake
  - requests  
  - rise
  - pip:
    - git+https://github.com/intake/intake-stac