name: osm-github-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - cartopy
  - geoviews
  - h5netcdf
  - hvplot
  - numpy
  - matplotlib
  - xarray
  - intake
  - intake-stac
  - sat-search
  - requests  
  - rise